lower_bound_premise = 6
upper_bound_premise = 10
lower_bound_hypothesis = 1
upper_bound_hypothesis = 10

# the hypothesis talks about the range of random integers generated by Colin's app, which is also mentioned in the premise
if lower_bound_hypothesis >= lower_bound_premise:
    # check if the lower bound of the range in the hypothesis contradicts the lower bound of the range in the premise
    label = "contradiction"
elif upper_bound_hypothesis != upper_bound_premise:
    # check if the upper bound of the range in the hypothesis contradicts the upper bound of the range in the premise
    label = "contradiction"
else:
    # the premise gives only an estimate for the lower bound of the range
    # any lower bound less than 'lower_bound_premise' is consistent with the premise, but cannot be explicitly entailed from the premise
    label = "neutral"

print(label)
